### ISSUE TITLE
Error in File model_evaluation.py

### ISSUE THREAD

**Issue by ankur220693** [aneesh-joshi/LSTM_POS_Tagger#17]
****
**tokenized_sentence.append(word2int[word])**
**KeyError: 'बुधिनाथ'**
Script is:

from keras.models import load_model
import pickle
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical

with open('data.pkl', 'rb') as f:
	X_train, Y_train, word2int, int2word, tag2int, int2tag = pickle.load(f)

	del X_train
	del Y_train

sentence ='बुधिनाथ पढ़लैन आ सभ कियो सुनला'.split()

tokenized_sentence = []

for word in sentence:
	tokenized_sentence.append(word2int[word])

tokenized_sentence = np.asarray([tokenized_sentence])
padded_tokenized_sentence = pad_sequences(tokenized_sentence, maxlen=100)

print('The sentence is ', sentence)
print('The tokenized sentence is ',tokenized_sentence)
print('The padded tokenized sentence is ', padded_tokenized_sentence)

model = load_model('Models/model.h5')

prediction = model.predict(padded_tokenized_sentence)

print(prediction.shape)

for i, pred in enumerate(prediction[0]):
	try:
		print(sentence[i], ' : ', int2tag[np.argmax(pred)])
	except:
		pass
		# print('NA')
![Screenshot from 2019-08-07 15-58-01](https://user-images.githubusercontent.com/39484784/62616081-5064e580-b92c-11e9-8531-a953e5932e62.png)

**Comment by aneesh-joshi** [comment]
Hi @ankur220693 
The word बुधिनाथ is not in the corpus.
Moreover, the model is trained on english words. It won't work on hindi words or words of any other language.

In my case, I used embeddings from pretrained word vectors of english.
You'll have to train embeddings for your language and use it with that.

Let me know if you have further questions. I am closing this issue for now.

**Comment by ankur220693** [comment]
I have my embedding file of dimension = 300, how should I implement it? The
file consist of word and corresponding vectors.

**Comment by rachitjain2706** [comment]
Hi @ankur220693 

You will first have to make a dictionary to use the word embeddings in which the key is the word and the value is the corresponding vector. 

It will look something like this 
dict_example['the'] = [0.05 0.1 ..... ]

To do this, you can run the file - make_glove_pickle.py. This file will create a dictionary of the word embeddings and store it as a pickle dump. You can directly use your word embeddings in the make_model.py

Let me know if you need further help.

**Comment by ankur220693** [comment]
Thanks a lot, definitely will let you know.

**Comment by aneesh-joshi** [comment]
@ankur220693 

Please look at work done by [@dutkaD](https://github.com/dutkaD) on the [ukranian pos tagger](https://github.com/dutkaD/ukrainian-pos-tagger)
May give you some ideas.

**Comment by ankur220693** [comment]
Sure, Thanks.
