### ISSUE TITLE
GPU configuration

### ISSUE THREAD

**Issue by Dharmanath** [aneesh-joshi/LSTM_POS_Tagger#9]
Is there any special configuration for usage of GPU?

**Comment by aneesh-joshi** [comment]
@Dharmanath 
No, there is no such configuration needed from my end 
If you can run other keras code on GPU, this should work as well.
Make sure you have `tensorflow-gpu` installed

If you want to test it with a smaller dataset, set the number of samples to 100 instead of 500

**Comment by aneesh-joshi** [comment]
Additionally, sequence models like LSTMs don't benefit as much from GPU as say CNNs

**Comment by aneesh-joshi** [comment]
Also, please look at the other branch. I have made some changes which I will integrate later.

**Comment by aneesh-joshi** [comment]
closing due to no response
